# CircleCI build config example for testing implementing the 
# Aqua Security MicroScanner

version: 2.1

orbs:
  microscanner: aquasecurity/microscanner@dev:0.1.3


jobs:
  docker-build:
    executor: microscanner/default
    steps:
      - checkout
      - run: docker build -t aquasec/peekr:latest .

workflows:
  scan-image:
    jobs:
      - docker-build
      - microscanner/scan-image:
          requires: 
            - docker-build
          context: microscanner
          image: aquasec/peekr:latest
          microscanner_options: "--continue-on-failure"
